-- Bucket para mídia do WhatsApp (imagens, áudios, etc.)
-- Execute no SQL Editor do Supabase
--
-- IMPORTANTE: Crie o bucket manualmente primeiro no Dashboard:
--   Storage → Create bucket → Nome: whatsapp-media → Public: false
--   File size limit: 50MB
--   Allowed MIME: image/*, audio/*, video/*, application/pdf
--
-- Depois execute migration-storage-private-buckets.sql para políticas RLS.
-- Upload é feito via service role (webhook); leitura via signed URL ou equipe autenticada.
