import type {
  ApiCategory,
  ApiEndpointDefinition,
  AuditRiskLevel,
  AuditScenario,
  AuthMechanism,
  HttpMethod,
  ProbeStrategy,
  SideEffect,
} from "./types";

type EndpointInput = {
  id: string;
  name: string;
  method: HttpMethod;
  path: string;
  file: string;
  category: ApiCategory;
  requiresAuth: boolean;
  requiresAuthorization?: boolean;
  requiredRoles?: string[];
  authMechanism: AuthMechanism;
  hasValidation?: boolean;
  auditRisk: AuditRiskLevel;
  auditFindingIds?: string[];
  probeStrategy?: ProbeStrategy;
  expectedAnonymousStatus?: number | number[];
  expectedStatusByRole?: Partial<Record<AuditScenario, number | number[]>>;
  queryParams?: Record<string, string>;
  sampleBody?: unknown;
  sideEffects?: SideEffect;
  notes?: string;
};

function e(input: EndpointInput): ApiEndpointDefinition {
  return {
    id: input.id,
    name: input.name,
    method: input.method,
    pathTemplate: input.path,
    file: input.file,
    category: input.category,
    requiresAuth: input.requiresAuth,
    requiresAuthorization: input.requiresAuthorization ?? input.requiresAuth,
    requiredRoles: input.requiredRoles ?? [],
    authMechanism: input.authMechanism,
    hasValidation: input.hasValidation ?? true,
    auditRisk: input.auditRisk,
    auditFindingIds: input.auditFindingIds ?? [],
    probeStrategy: input.probeStrategy ?? (input.requiresAuth ? "auth-only" : "full"),
    expectedAnonymousStatus:
      input.expectedAnonymousStatus ??
      (input.requiresAuth ? [401, 403, 500] : undefined),
    expectedStatusByRole: input.expectedStatusByRole,
    queryParams: input.queryParams,
    sampleBody: input.sampleBody,
    sideEffects: input.sideEffects ?? (input.method === "GET" ? "read" : "write"),
    notes: input.notes,
  };
}

export const API_AUDIT_REGISTRY: ApiEndpointDefinition[] = [
  // --- Públicos ---
  e({
    id: "plans-pricing-get",
    name: "Planos pricing",
    method: "GET",
    path: "/api/plans/pricing",
    file: "app/api/plans/pricing/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: 200,
    sideEffects: "read",
  }),
  e({
    id: "stripe-config-get",
    name: "Stripe config",
    method: "GET",
    path: "/api/stripe/config",
    file: "app/api/stripe/config/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [200, 500],
    sideEffects: "read",
  }),
  e({
    id: "stripe-price-get",
    name: "Stripe price",
    method: "GET",
    path: "/api/stripe/price",
    file: "app/api/stripe/price/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "baixo",
    probeStrategy: "full",
    queryParams: { plan: "pro" },
    expectedAnonymousStatus: [200, 500],
    sideEffects: "read",
  }),
  e({
    id: "public-booking-catalog-get",
    name: "Booking catalog",
    method: "GET",
    path: "/api/public/booking/[slug]/catalog",
    file: "app/api/public/booking/[slug]/catalog/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "medio",
    probeStrategy: "full",
    expectedAnonymousStatus: [200, 404, 429],
    sideEffects: "read",
  }),
  e({
    id: "public-booking-slots-get",
    name: "Booking slots",
    method: "GET",
    path: "/api/public/booking/[slug]/slots",
    file: "app/api/public/booking/[slug]/slots/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    queryParams: { procedureId: "{planId}", doctorId: "{planId}" },
    expectedAnonymousStatus: [400, 404, 429],
    sideEffects: "read",
  }),
  e({
    id: "public-booking-appointments-post",
    name: "Booking appointments",
    method: "POST",
    path: "/api/public/booking/[slug]/appointments",
    file: "app/api/public/booking/[slug]/appointments/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 404, 429],
    sideEffects: "write",
  }),
  e({
    id: "public-contact-post",
    name: "Public contact",
    method: "POST",
    path: "/api/public/contact/[slug]",
    file: "app/api/public/contact/[slug]/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 404, 429],
    sideEffects: "write",
  }),
  e({
    id: "public-suggestions-get",
    name: "Public suggestions list",
    method: "GET",
    path: "/api/public-suggestions",
    file: "app/api/public-suggestions/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "service-role",
    auditRisk: "medio",
    probeStrategy: "full",
    expectedAnonymousStatus: [200, 500],
    sideEffects: "read",
  }),
  e({
    id: "public-suggestions-post",
    name: "Public suggestions create",
    method: "POST",
    path: "/api/public-suggestions",
    file: "app/api/public-suggestions/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "service-role",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 429],
    sideEffects: "write",
  }),
  e({
    id: "public-suggestions-id-patch",
    name: "Public suggestions patch",
    method: "PATCH",
    path: "/api/public-suggestions/[id]",
    file: "app/api/public-suggestions/[id]/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "edit-token",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 401, 403],
    sideEffects: "write",
  }),
  e({
    id: "public-suggestions-id-delete",
    name: "Public suggestions delete",
    method: "DELETE",
    path: "/api/public-suggestions/[id]",
    file: "app/api/public-suggestions/[id]/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "edit-token",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 401, 403],
    sideEffects: "write",
  }),
  e({
    id: "public-suggestions-token-get",
    name: "Public suggestions by token",
    method: "GET",
    path: "/api/public-suggestions/token/[token]",
    file: "app/api/public-suggestions/token/[token]/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "edit-token",
    auditRisk: "medio",
    probeStrategy: "full",
    expectedAnonymousStatus: [200, 404],
    sideEffects: "read",
  }),
  e({
    id: "public-suggestions-token-patch",
    name: "Public suggestions token patch",
    method: "PATCH",
    path: "/api/public-suggestions/token/[token]",
    file: "app/api/public-suggestions/token/[token]/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "edit-token",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 404],
    sideEffects: "write",
  }),
  e({
    id: "public-suggestions-token-delete",
    name: "Public suggestions token delete",
    method: "DELETE",
    path: "/api/public-suggestions/token/[token]",
    file: "app/api/public-suggestions/token/[token]/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "edit-token",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 404],
    sideEffects: "write",
  }),
  e({
    id: "public-form-submit-post",
    name: "Public form submit",
    method: "POST",
    path: "/api/public/form/submit",
    file: "app/api/public/form/submit/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [400, 429],
    sampleBody: {
      template_id: "00000000-0000-0000-0000-000000000000",
      submitter_name: "Teste",
      submitter_email: "teste@example.com",
    },
    sideEffects: "write",
    notes: "Submit + auto-send server-side; rate limit por IP",
  }),
  e({
    id: "process-public-form-event-post",
    name: "Process public form event (deprecated)",
    method: "POST",
    path: "/api/process-public-form-event",
    file: "app/api/process-public-form-event/route.ts",
    category: "publico",
    requiresAuth: false,
    authMechanism: "none",
    auditRisk: "baixo",
    auditFindingIds: ["V-004"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 410,
    sideEffects: "none",
    notes: "Descontinuado — retorna 410 Gone",
  }),
  e({
    id: "whatsapp-webhook-debug-get",
    name: "WhatsApp webhook debug",
    method: "GET",
    path: "/api/whatsapp/webhook/debug",
    file: "app/api/whatsapp/webhook/debug/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "critico",
    auditFindingIds: ["V-002"],
    probeStrategy: "full",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: 200 },
    sideEffects: "read",
    notes: "Protegido por CRON_SECRET — não expor sem autenticação",
  }),

  // --- Webhooks ---
  e({
    id: "stripe-webhook-post",
    name: "Stripe webhook",
    method: "POST",
    path: "/api/stripe/webhook",
    file: "app/api/stripe/webhook/route.ts",
    category: "webhook",
    requiresAuth: false,
    authMechanism: "stripe-signature",
    auditRisk: "baixo",
    probeStrategy: "manual",
    expectedAnonymousStatus: [400, 500],
    notes: "Requer assinatura Stripe",
  }),
  e({
    id: "integrations-whatsapp-webhook-get",
    name: "Meta WhatsApp webhook verify",
    method: "GET",
    path: "/api/integrations/whatsapp/webhook",
    file: "app/api/integrations/whatsapp/webhook/route.ts",
    category: "webhook",
    requiresAuth: false,
    authMechanism: "meta-verify",
    auditRisk: "medio",
    auditFindingIds: ["V-005"],
    probeStrategy: "full",
    queryParams: {
      "hub.mode": "subscribe",
      "hub.verify_token": "{metaVerifyToken}",
      "hub.challenge": "audit-challenge",
    },
    expectedAnonymousStatus: [200, 403],
    sideEffects: "none",
  }),
  e({
    id: "integrations-whatsapp-webhook-post",
    name: "Meta WhatsApp webhook POST",
    method: "POST",
    path: "/api/integrations/whatsapp/webhook",
    file: "app/api/integrations/whatsapp/webhook/route.ts",
    category: "webhook",
    requiresAuth: false,
    authMechanism: "meta-signature",
    auditRisk: "baixo",
    probeStrategy: "manual",
    expectedAnonymousStatus: [401, 500],
  }),
  e({
    id: "whatsapp-webhook-get",
    name: "WhatsApp webhook verify (legacy)",
    method: "GET",
    path: "/api/whatsapp/webhook",
    file: "app/api/whatsapp/webhook/route.ts",
    category: "webhook",
    requiresAuth: false,
    authMechanism: "meta-verify",
    auditRisk: "medio",
    auditFindingIds: ["V-016"],
    probeStrategy: "full",
    queryParams: {
      "hub.mode": "subscribe",
      "hub.verify_token": "{metaVerifyToken}",
      "hub.challenge": "audit-challenge",
    },
    expectedAnonymousStatus: [200, 403],
    sideEffects: "none",
  }),
  e({
    id: "whatsapp-webhook-post",
    name: "WhatsApp webhook POST (legacy)",
    method: "POST",
    path: "/api/whatsapp/webhook",
    file: "app/api/whatsapp/webhook/route.ts",
    category: "webhook",
    requiresAuth: false,
    authMechanism: "meta-signature",
    auditRisk: "baixo",
    probeStrategy: "manual",
    expectedAnonymousStatus: [401, 500],
  }),

  // --- Cron / Internal ---
  e({
    id: "cron-process-whatsapp-ai-get",
    name: "Cron process WhatsApp AI",
    method: "GET",
    path: "/api/cron/process-whatsapp-ai",
    file: "app/api/cron/process-whatsapp-ai/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "alto",
    auditFindingIds: ["V-006"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: 200 },
    sideEffects: "write",
  }),
  e({
    id: "cron-financial-recurrence-get",
    name: "Cron financial recurrence",
    method: "GET",
    path: "/api/cron/financial-recurrence",
    file: "app/api/cron/financial-recurrence/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "alto",
    auditFindingIds: ["V-006"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: 200 },
    sideEffects: "write",
  }),
  e({
    id: "cron-check-compliance-get",
    name: "Cron check compliance",
    method: "GET",
    path: "/api/cron/check-compliance",
    file: "app/api/cron/check-compliance/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "alto",
    auditFindingIds: ["V-006"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: 200 },
    sideEffects: "write",
  }),
  e({
    id: "cron-close-whatsapp-expired-get",
    name: "Cron close WhatsApp expired",
    method: "GET",
    path: "/api/cron/close-whatsapp-expired",
    file: "app/api/cron/close-whatsapp-expired/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "alto",
    auditFindingIds: ["V-006"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: 200 },
    sideEffects: "write",
  }),
  e({
    id: "cron-virtual-assistant-confirmations-get",
    name: "Cron virtual assistant confirmations",
    method: "GET",
    path: "/api/cron/virtual-assistant-confirmations",
    file: "app/api/cron/virtual-assistant-confirmations/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "alto",
    auditFindingIds: ["V-006"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: 200 },
    sideEffects: "write",
  }),
  e({
    id: "internal-process-whatsapp-ai-post",
    name: "Internal process WhatsApp AI",
    method: "POST",
    path: "/api/internal/process-whatsapp-ai",
    file: "app/api/internal/process-whatsapp-ai/route.ts",
    category: "cron",
    requiresAuth: true,
    authMechanism: "cron-secret",
    auditRisk: "alto",
    auditFindingIds: ["V-007"],
    probeStrategy: "auth-only",
    expectedAnonymousStatus: 401,
    expectedStatusByRole: { cron_authenticated: [200, 400] },
    sideEffects: "write",
  }),

  // --- System admin ---
  e({
    id: "admin-plans-post",
    name: "Admin create plan",
    method: "POST",
    path: "/api/admin/plans",
    file: "app/api/admin/plans/route.ts",
    category: "sistema",
    requiresAuth: true,
    requiredRoles: ["system_admin"],
    authMechanism: "helper-system-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 404],
    sideEffects: "write",
  }),
  e({
    id: "admin-plans-id-put",
    name: "Admin update plan",
    method: "PUT",
    path: "/api/admin/plans/[id]",
    file: "app/api/admin/plans/[id]/route.ts",
    category: "sistema",
    requiresAuth: true,
    requiredRoles: ["system_admin"],
    authMechanism: "helper-system-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 404],
    sideEffects: "write",
  }),
  e({
    id: "admin-plans-id-delete",
    name: "Admin delete plan",
    method: "DELETE",
    path: "/api/admin/plans/[id]",
    file: "app/api/admin/plans/[id]/route.ts",
    category: "sistema",
    requiresAuth: true,
    requiredRoles: ["system_admin"],
    authMechanism: "helper-system-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 404],
    sideEffects: "write",
  }),
  e({
    id: "admin-clinics-id-put",
    name: "Admin update clinic",
    method: "PUT",
    path: "/api/admin/clinics/[id]",
    file: "app/api/admin/clinics/[id]/route.ts",
    category: "sistema",
    requiresAuth: true,
    requiredRoles: ["system_admin"],
    authMechanism: "helper-system-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 404],
    sideEffects: "write",
  }),
  e({
    id: "admin-reset-stripe-post",
    name: "Admin reset Stripe",
    method: "POST",
    path: "/api/admin/reset-stripe",
    file: "app/api/admin/reset-stripe/route.ts",
    category: "sistema",
    requiresAuth: true,
    requiredRoles: ["system_admin"],
    authMechanism: "helper-system-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 404],
    sideEffects: "write",
  }),

  // --- Stripe clinic admin ---
  ...[
    ["stripe-subscription-get", "Stripe subscription", "GET", "/api/stripe/subscription", "app/api/stripe/subscription/route.ts"],
    ["stripe-invoices-get", "Stripe invoices", "GET", "/api/stripe/invoices", "app/api/stripe/invoices/route.ts"],
  ].map(([id, name, method, path, file]) =>
    e({
      id: id as string,
      name: name as string,
      method: method as HttpMethod,
      path: path as string,
      file: file as string,
      category: "administrador",
      requiresAuth: true,
      requiredRoles: ["admin"],
      authMechanism: "getUser-admin",
      auditRisk: "baixo",
      probeStrategy: "full",
      expectedAnonymousStatus: [401, 403],
      sideEffects: "read",
    })
  ),
  ...[
    ["stripe-create-checkout-session-post", "Stripe checkout session", "/api/stripe/create-checkout-session"],
    ["stripe-create-payment-intent-post", "Stripe payment intent", "/api/stripe/create-payment-intent"],
    ["stripe-confirm-subscription-post", "Stripe confirm subscription", "/api/stripe/confirm-subscription"],
    ["stripe-create-portal-session-post", "Stripe portal session", "/api/stripe/create-portal-session"],
    ["stripe-change-plan-post", "Stripe change plan", "/api/stripe/change-plan"],
    ["stripe-checkout-change-plan-post", "Stripe checkout change plan", "/api/stripe/checkout-change-plan"],
    ["stripe-cancel-subscription-post", "Stripe cancel subscription", "/api/stripe/cancel-subscription"],
    ["stripe-resume-subscription-post", "Stripe resume subscription", "/api/stripe/resume-subscription"],
  ].map(([id, name, path]) =>
    e({
      id: id as string,
      name: name as string,
      method: "POST",
      path: path as string,
      file: `app/api${(path as string).replace("/api", "")}/route.ts`,
      category: "administrador",
      requiresAuth: true,
      requiredRoles: ["admin"],
      authMechanism: "getUser-admin",
      auditRisk: "baixo",
      probeStrategy: "auth-only",
      expectedAnonymousStatus: [401, 403],
      sideEffects: "write",
    })
  ),

  // --- Integrations ---
  e({
    id: "integrations-get",
    name: "List integrations",
    method: "GET",
    path: "/api/integrations",
    file: "app/api/integrations/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-google-auth-get",
    name: "Google OAuth start",
    method: "GET",
    path: "/api/integrations/google/auth",
    file: "app/api/integrations/google/auth/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-google-callback-get",
    name: "Google OAuth callback",
    method: "GET",
    path: "/api/integrations/google/callback",
    file: "app/api/integrations/google/callback/route.ts",
    category: "administrador",
    requiresAuth: true,
    authMechanism: "oauth-callback",
    auditRisk: "baixo",
    probeStrategy: "manual",
    expectedAnonymousStatus: [400, 401, 403],
    notes: "Requer code/state OAuth",
  }),
  e({
    id: "integrations-google-disconnect-post",
    name: "Google disconnect",
    method: "POST",
    path: "/api/integrations/google/disconnect",
    file: "app/api/integrations/google/disconnect/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-email-test-post",
    name: "Email integration test",
    method: "POST",
    path: "/api/integrations/email/test",
    file: "app/api/integrations/email/test/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-auth-get",
    name: "WhatsApp OAuth start",
    method: "GET",
    path: "/api/integrations/whatsapp/auth",
    file: "app/api/integrations/whatsapp/auth/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-whatsapp-callback-get",
    name: "WhatsApp OAuth callback",
    method: "GET",
    path: "/api/integrations/whatsapp/callback",
    file: "app/api/integrations/whatsapp/callback/route.ts",
    category: "administrador",
    requiresAuth: true,
    authMechanism: "oauth-callback",
    auditRisk: "baixo",
    probeStrategy: "manual",
    expectedAnonymousStatus: [400, 401, 403],
  }),
  e({
    id: "integrations-whatsapp-complete-embedded-post",
    name: "WhatsApp embedded signup",
    method: "POST",
    path: "/api/integrations/whatsapp/complete-embedded",
    file: "app/api/integrations/whatsapp/complete-embedded/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-disconnect-post",
    name: "WhatsApp disconnect",
    method: "POST",
    path: "/api/integrations/whatsapp/disconnect",
    file: "app/api/integrations/whatsapp/disconnect/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-test-post",
    name: "WhatsApp test send",
    method: "POST",
    path: "/api/integrations/whatsapp/test",
    file: "app/api/integrations/whatsapp/test/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-billing-status-get",
    name: "WhatsApp billing status",
    method: "GET",
    path: "/api/integrations/whatsapp/billing-status",
    file: "app/api/integrations/whatsapp/billing-status/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-whatsapp-meta-assets-get",
    name: "WhatsApp meta assets",
    method: "GET",
    path: "/api/integrations/whatsapp/meta-assets",
    file: "app/api/integrations/whatsapp/meta-assets/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-whatsapp-set-phone-id-post",
    name: "WhatsApp set phone id",
    method: "POST",
    path: "/api/integrations/whatsapp/set-phone-id",
    file: "app/api/integrations/whatsapp/set-phone-id/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-simple-auth-get",
    name: "WhatsApp simple auth",
    method: "GET",
    path: "/api/integrations/whatsapp-simple/auth",
    file: "app/api/integrations/whatsapp-simple/auth/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-whatsapp-simple-callback-get",
    name: "WhatsApp simple callback",
    method: "GET",
    path: "/api/integrations/whatsapp-simple/callback",
    file: "app/api/integrations/whatsapp-simple/callback/route.ts",
    category: "administrador",
    requiresAuth: true,
    authMechanism: "oauth-callback",
    auditRisk: "baixo",
    probeStrategy: "manual",
    expectedAnonymousStatus: [400, 401, 403],
  }),
  e({
    id: "integrations-whatsapp-simple-disconnect-post",
    name: "WhatsApp simple disconnect",
    method: "POST",
    path: "/api/integrations/whatsapp-simple/disconnect",
    file: "app/api/integrations/whatsapp-simple/disconnect/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-simple-discover-phone-id-post",
    name: "WhatsApp simple discover phone",
    method: "POST",
    path: "/api/integrations/whatsapp-simple/discover-phone-id",
    file: "app/api/integrations/whatsapp-simple/discover-phone-id/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "read",
  }),
  e({
    id: "integrations-whatsapp-simple-register-post",
    name: "WhatsApp simple register",
    method: "POST",
    path: "/api/integrations/whatsapp-simple/register",
    file: "app/api/integrations/whatsapp-simple/register/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),
  e({
    id: "integrations-whatsapp-simple-set-phone-id-post",
    name: "WhatsApp simple set phone id",
    method: "POST",
    path: "/api/integrations/whatsapp-simple/set-phone-id",
    file: "app/api/integrations/whatsapp-simple/set-phone-id/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403],
    sideEffects: "write",
  }),

  // --- Patients / Appointments ---
  e({
    id: "patients-search-get",
    name: "Patients search",
    method: "GET",
    path: "/api/patients/search",
    file: "app/api/patients/search/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "full",
    queryParams: { q: "test" },
    expectedAnonymousStatus: [401, 500],
    sideEffects: "read",
  }),
  e({
    id: "patients-by-phone-get",
    name: "Patients by phone",
    method: "GET",
    path: "/api/patients/by-phone",
    file: "app/api/patients/by-phone/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    queryParams: { phone: "11999999999" },
    expectedAnonymousStatus: [401, 400, 500],
    sideEffects: "read",
  }),
  e({
    id: "patients-custom-fields-get",
    name: "Patients custom fields",
    method: "GET",
    path: "/api/patients/custom-fields",
    file: "app/api/patients/custom-fields/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "read",
  }),
  e({
    id: "appointments-transcribe-post",
    name: "Appointment transcribe",
    method: "POST",
    path: "/api/appointments/[id]/transcribe",
    file: "app/api/appointments/[id]/transcribe/route.ts",
    category: "autenticado",
    requiresAuth: true,
    requiredRoles: ["admin", "secretaria", "medico"],
    authMechanism: "helper-clinic-member-role",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "write",
  }),
  e({
    id: "appointments-transcriptions-get",
    name: "Appointment transcriptions",
    method: "GET",
    path: "/api/appointments/[id]/transcriptions",
    file: "app/api/appointments/[id]/transcriptions/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member-role",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 404, 500],
    sideEffects: "read",
  }),
  e({
    id: "transcribe-jobs-get",
    name: "Transcribe job status",
    method: "GET",
    path: "/api/transcribe/jobs/[transcriptionId]",
    file: "app/api/transcribe/jobs/[transcriptionId]/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member-role",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 404, 500],
    sideEffects: "read",
  }),

  // --- WhatsApp dashboard ---
  e({
    id: "whatsapp-conversations-get",
    name: "WhatsApp conversations",
    method: "GET",
    path: "/api/whatsapp/conversations",
    file: "app/api/whatsapp/conversations/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-messages-get",
    name: "WhatsApp messages",
    method: "GET",
    path: "/api/whatsapp/messages",
    file: "app/api/whatsapp/messages/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    queryParams: { conversationId: "{conversationId}" },
    expectedAnonymousStatus: [401, 400, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-unread-count-get",
    name: "WhatsApp unread count",
    method: "GET",
    path: "/api/whatsapp/unread-count",
    file: "app/api/whatsapp/unread-count/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-secretaries-get",
    name: "WhatsApp secretaries",
    method: "GET",
    path: "/api/whatsapp/secretaries",
    file: "app/api/whatsapp/secretaries/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-usage-limit-get",
    name: "WhatsApp usage limit",
    method: "GET",
    path: "/api/whatsapp/usage-limit",
    file: "app/api/whatsapp/usage-limit/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-mark-viewed-post",
    name: "WhatsApp mark viewed",
    method: "POST",
    path: "/api/whatsapp/mark-viewed",
    file: "app/api/whatsapp/mark-viewed/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-complete-conversation-post",
    name: "WhatsApp complete conversation",
    method: "POST",
    path: "/api/whatsapp/complete-conversation",
    file: "app/api/whatsapp/complete-conversation/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-delete-conversation-delete",
    name: "WhatsApp delete conversation",
    method: "DELETE",
    path: "/api/whatsapp/delete-conversation",
    file: "app/api/whatsapp/delete-conversation/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-close-expired-post",
    name: "WhatsApp close expired",
    method: "POST",
    path: "/api/whatsapp/close-expired",
    file: "app/api/whatsapp/close-expired/route.ts",
    category: "autenticado",
    requiresAuth: true,
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-send-post",
    name: "WhatsApp send message",
    method: "POST",
    path: "/api/whatsapp/send",
    file: "app/api/whatsapp/send/route.ts",
    category: "autenticado",
    requiresAuth: true,
    requiredRoles: ["admin", "secretaria"],
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-link-patient-post",
    name: "WhatsApp link patient",
    method: "POST",
    path: "/api/whatsapp/link-patient",
    file: "app/api/whatsapp/link-patient/route.ts",
    category: "autenticado",
    requiresAuth: true,
    requiredRoles: ["admin", "secretaria"],
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-assign-conversation-post",
    name: "WhatsApp assign conversation",
    method: "POST",
    path: "/api/whatsapp/assign-conversation",
    file: "app/api/whatsapp/assign-conversation/route.ts",
    category: "autenticado",
    requiresAuth: true,
    requiredRoles: ["admin", "secretaria"],
    authMechanism: "helper-clinic-member",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-routing-settings-get",
    name: "WhatsApp routing settings get",
    method: "GET",
    path: "/api/whatsapp/routing-settings",
    file: "app/api/whatsapp/routing-settings/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-routing-settings-post",
    name: "WhatsApp routing settings post",
    method: "POST",
    path: "/api/whatsapp/routing-settings",
    file: "app/api/whatsapp/routing-settings/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "baixo",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-assistant-diagnostics-get",
    name: "WhatsApp assistant diagnostics",
    method: "GET",
    path: "/api/whatsapp/assistant/diagnostics",
    file: "app/api/whatsapp/assistant/diagnostics/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "medio",
    probeStrategy: "full",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "read",
  }),
  e({
    id: "whatsapp-assistant-simulate-post",
    name: "WhatsApp assistant simulate",
    method: "POST",
    path: "/api/whatsapp/assistant/simulate",
    file: "app/api/whatsapp/assistant/simulate/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-assistant-execute-tool-post",
    name: "WhatsApp assistant execute tool",
    method: "POST",
    path: "/api/whatsapp/assistant/execute-tool",
    file: "app/api/whatsapp/assistant/execute-tool/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "alto",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-assistant-process-now-post",
    name: "WhatsApp assistant process now",
    method: "POST",
    path: "/api/whatsapp/assistant/process-now",
    file: "app/api/whatsapp/assistant/process-now/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-assistant-clear-queue-post",
    name: "WhatsApp assistant clear queue",
    method: "POST",
    path: "/api/whatsapp/assistant/clear-queue",
    file: "app/api/whatsapp/assistant/clear-queue/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
  e({
    id: "whatsapp-assistant-reactivate-post",
    name: "WhatsApp assistant reactivate",
    method: "POST",
    path: "/api/whatsapp/assistant/reactivate-conversation",
    file: "app/api/whatsapp/assistant/reactivate-conversation/route.ts",
    category: "administrador",
    requiresAuth: true,
    requiredRoles: ["admin"],
    authMechanism: "helper-clinic-admin",
    auditRisk: "medio",
    probeStrategy: "auth-only",
    expectedAnonymousStatus: [401, 403, 500],
    sideEffects: "write",
  }),
];

export function getEndpointById(id: string): ApiEndpointDefinition | undefined {
  return API_AUDIT_REGISTRY.find((entry) => entry.id === id);
}

export function getRegistryStats() {
  const publicCount = API_AUDIT_REGISTRY.filter((x) => x.category === "publico").length;
  const adminCount = API_AUDIT_REGISTRY.filter(
    (x) => x.category === "administrador" || x.category === "sistema"
  ).length;
  const privateCount = API_AUDIT_REGISTRY.filter(
    (x) => x.requiresAuth && x.category !== "cron" && x.category !== "webhook"
  ).length;
  return {
    total: API_AUDIT_REGISTRY.length,
    publicCount,
    adminCount,
    privateCount,
  };
}
